name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Running publish script
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          scripts/publish.sh
