name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Running publish script
        run: |
          git config --global user.name "Jocelyn MEYRON"
          git config --global user.email Jocelyn.Meyron@insa-lyon.fr
          scripts/publish.sh
      - name: Pushing changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "gh-pages"
          force: true
          directory: "website"
