name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Running publish script
        run: |
          git config --global user.email "Jocelyn.Meyron@insa-lyon.fr"
          git config --global user.name "Jocelyn MEYRON"
          scripts/publish.sh
